// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcPhone.Data;

namespace MvcPhone.Migrations
{
    [DbContext(typeof(MvcPhoneContext))]
    partial class MvcPhoneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcPhone.Models.Category", b =>
                {
                    b.Property<int>("idLSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("maloai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenloai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLSP");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("MvcPhone.Models.Customer", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matkhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("matkhaunhaplai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("tendangnhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUser");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MvcPhone.Models.Order", b =>
                {
                    b.Property<int>("idHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomersidUser")
                        .HasColumnType("int");

                    b.Property<string>("diachi_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gmail_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("payment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("tongtien")
                        .HasColumnType("real");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("idHD");

                    b.HasIndex("CustomersidUser");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MvcPhone.Models.OrderDetail", b =>
                {
                    b.Property<int>("idCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrdersidHD")
                        .HasColumnType("int");

                    b.Property<int?>("ProductsidSP")
                        .HasColumnType("int");

                    b.Property<float>("dongia")
                        .HasColumnType("real");

                    b.Property<int>("idHD")
                        .HasColumnType("int");

                    b.Property<int>("idSP")
                        .HasColumnType("int");

                    b.Property<float>("khuyenmai")
                        .HasColumnType("real");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.Property<float>("thanhtien")
                        .HasColumnType("real");

                    b.HasKey("idCTHD");

                    b.HasIndex("OrdersidHD");

                    b.HasIndex("ProductsidSP");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("MvcPhone.Models.Product", b =>
                {
                    b.Property<int>("idSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategorysidLSP")
                        .HasColumnType("int");

                    b.Property<float>("gia")
                        .HasColumnType("real");

                    b.Property<string>("hinhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idLSP")
                        .HasColumnType("int");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSP");

                    b.HasIndex("CategorysidLSP");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MvcPhone.Models.Worker", b =>
                {
                    b.Property<int>("STT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategorysidLSP")
                        .HasColumnType("int");

                    b.Property<int?>("CustomersidUser")
                        .HasColumnType("int");

                    b.Property<int?>("OrderDetailsidCTHD")
                        .HasColumnType("int");

                    b.Property<int?>("OrdersidHD")
                        .HasColumnType("int");

                    b.Property<int?>("ProductsidSP")
                        .HasColumnType("int");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("luong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phanquyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STT");

                    b.HasIndex("CategorysidLSP");

                    b.HasIndex("CustomersidUser");

                    b.HasIndex("OrderDetailsidCTHD");

                    b.HasIndex("OrdersidHD");

                    b.HasIndex("ProductsidSP");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("MvcPhone.Models.Order", b =>
                {
                    b.HasOne("MvcPhone.Models.Customer", "Customers")
                        .WithMany("Orders")
                        .HasForeignKey("CustomersidUser");
                });

            modelBuilder.Entity("MvcPhone.Models.OrderDetail", b =>
                {
                    b.HasOne("MvcPhone.Models.Order", "Orders")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrdersidHD");

                    b.HasOne("MvcPhone.Models.Product", "Products")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductsidSP");
                });

            modelBuilder.Entity("MvcPhone.Models.Product", b =>
                {
                    b.HasOne("MvcPhone.Models.Category", "Categorys")
                        .WithMany("Products")
                        .HasForeignKey("CategorysidLSP");
                });

            modelBuilder.Entity("MvcPhone.Models.Worker", b =>
                {
                    b.HasOne("MvcPhone.Models.Category", "Categorys")
                        .WithMany()
                        .HasForeignKey("CategorysidLSP");

                    b.HasOne("MvcPhone.Models.Customer", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomersidUser");

                    b.HasOne("MvcPhone.Models.OrderDetail", "OrderDetails")
                        .WithMany()
                        .HasForeignKey("OrderDetailsidCTHD");

                    b.HasOne("MvcPhone.Models.Order", "Orders")
                        .WithMany()
                        .HasForeignKey("OrdersidHD");

                    b.HasOne("MvcPhone.Models.Product", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsidSP");
                });
#pragma warning restore 612, 618
        }
    }
}
